name: tasilla
description: "TASILLA — Teachers And Schools International Language Learning Application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# The version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number is used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# In Windows, build-name is used as the major, minor, and patch parts of the product and file versions.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.6.0
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.12.4
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  record: ^7.1.1
  web: ^1.1.1
  path_provider: ^2.1.5
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/audio/a1/
    - assets/content/a1/
